### ISSUE TITLE
MMM, not sure what is this for

### ISSUE THREAD

**Issue by Demegorash** [Bloatware-WarevilleTHM/C2-Server#2]
I found this and created the server.... was able to go inside mine, but was not able to go to http://papash3ll.thm:8000/login

 The user and password found was not working for me... however I was afraid to go more deep... waiting for instructions!!!

**Comment by Fillup99999** [comment]
That's not a real URL that's why it didn't work. How were you able to get the server working? I got a 500 error and login.html not found.

**Comment by Leokratis** [comment]
I did manage to make it work. If you go on the instance IP (the one you used for the mp3 converter) and go on the port 8000 /login you will see the "admin" panel from the C2 server. After that you can crack the password (which I did though cookie injection, seeing as we have the encryption key) and I managed to log in.
![image](https://github.com/user-attachments/assets/27a60c04-bb04-499f-bf40-a18147861bca)

I am not aware of any other easter eggs in this website so I just assume it was just another run little project outside of the event.

**Comment by Leokratis** [comment]
> That's not a real URL that's why it didn't work. How were you able to get the server working? I got a 500 error and login.html not found.

I assume that when he said he created the server he meant that he used the code from the C2-Server on github and made it work. I did do this too, only to get the cookie though. After that I injected the cookie to `http://spotvm_ip:8000/login`

**Comment by d3c1m470r** [comment]
i didnt manage to get the cookie injection done, the server just rejected whatever i tried. nvm i tried to do it anyways in hopes of getting the ticket for the side quest but it guess it needs to be found elsewhere then

**Comment by Adventofcybersidequesthunter** [comment]
How are you guys even getting the cookie injection? I can't even get that to work :/

**Comment by Fillup99999** [comment]
You’re on the right track

**Comment by Leokratis** [comment]
> i didnt manage to get the cookie injection done, the server just rejected whatever i tried. nvm i tried to do it anyways in hopes of getting the ticket for the side quest but it guess it needs to be found elsewhere then

What? There is a side quest?
